name: Update LeetCode Solutions README
on:
  push:
    branches: [master]

  workflow_dispatch: # 允许手动触发

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: pip install black

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          auto_fix: true
          black: true
          black_auto_fix: true
          flake8: false
          flake8_auto_fix: false

      - name: Generate README with solutions
        run: |
          python generate_readme.py
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
